project_name: external-dns-ionos-webhook
version: 2

before:
  hooks:
    - scripts/release_precheck.sh

builds:
  - main: ./cmd/webhook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

    ldflags:
      - -X 'main.Version={{.Version}}'
      - -X 'main.Gitsha={{.ShortCommit}}'
archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: [zip]
dockers_v2:
  - id: external-dns-ionos-webhook
    images:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}"
    tags:
      - "{{ .Tag }}"
      - latest
      - "{{ .ShortCommit }}"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "ionos DNS webhook for external-dns"
      "org.opencontainers.image.url": "https://{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY}}"
      "org.opencontainers.image.source": "https://{{ .Env.GITHUB_SERVER_URL }}/{{ .Env.GITHUB_REPOSITORY}}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ time \"2006-01-02T15:04:05Z07:00\" }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "Apache-2.0"
checksum:
  disable: false
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

docker_signs:
  - cmd: cosign
    args:
      - sign
      - --tlog-upload=false
      - --key
      - env://COSIGN_PRIVATE_KEY
      - "${artifact}@${digest}"
      - --yes
    artifacts: images
    ids:
      - external-dns-ionos-webhook
    output: true

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
