image:
  tag: v0.15.1

sources:
  - ingress
  - service
  - crd

logLevel: debug

namespaced: false

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/ionos-cloud/external-dns-ionos-webhook
      tag: v0.7.1
      pullPolicy: Always
    ports:
      - containerPort: 8888
        name: http-webhook
        hostPort: 8888
        protocol: TCP
      - containerPort: 8080
        hostPort: 8080
        name: http-health-metrics
        protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
      - name: LOG_LEVEL
        value: debug
      - name: LOG_FORMAT
        value: txt
      # use DRY_RUN set to false when you want to test the webhook with applying changes to your DNS records
      - name: DRY_RUN
        value: "true"
      #      - name: DOMAIN_FILTER
      #        value: "test.com,test.de"
      #      - name: EXCLUDE_DOMAIN_FILTER
      #        value: "test.com,test.de"
      #      - name: REGEXP_DOMAIN_FILTER
      #        value: ""
      #      - name: REGEXP_DOMAIN_FILTER_EXCLUSION
      #        value: ""
      - name: IONOS_API_KEY
        valueFrom:
          secretKeyRef:
            name: ionos-credentials
            key: api-key
      - name: IONOS_DEBUG
        value: "false"
# the following values are derived automatically from the api key
#      - name: IONOS_API_URL
#        value: "https://api.hosting.ionos.com/dns"
#      - name: IONOS_AUTH_HEADER
#        value: "X-API-Key"
