image:
  tag: v0.15.1

sources: 
  - ingress
  - service
  - crd

logLevel: debug

namespaced: false

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/ionos-cloud/external-dns-ionos-webhook
      tag: v0.6.3
      pullPolicy: Always
    ports:
      - containerPort: 8080
        name: http-health
    livenessProbe:
      httpGet:
        path: /health
        targetPort: http-health
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /health
        targetPort: http-health
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
      - name: LOG_LEVEL
        value: debug
      - name: LOG_FORMAT
        value: txt
# use DRY_RUN set to true when you want to test the webhook without actually making changes to your DNS records
      - name: DRY_RUN
        value: "false"
#      - name: DOMAIN_FILTER
#        value: "test.com,test.de"
#      - name: EXCLUDE_DOMAIN_FILTER
#        value: "test.com,test.de"
#      - name: REGEXP_DOMAIN_FILTER
#        value: ""
#      - name: REGEXP_DOMAIN_FILTER_EXCLUSION
#        value: ""
      - name: IONOS_API_KEY
        valueFrom:
          secretKeyRef:
            name: ionos-credentials
            key: api-key
      - name: IONOS_DEBUG
        value: "false"
# the following values are derived automatically from the api key
#      - name: IONOS_API_URL
#        value: "https://api.hosting.ionos.com/dns"
#      - name: IONOS_AUTH_HEADER
#        value: "X-API-Key"
