image:
  tag: v0.15.1

sources: 
  - service
  - ingress
  - crd

logLevel: debug

namespaced: false

provider:
  name: webhook
  webhook:
    image:
      repository: localhost:5001/external-dns-ionos-webhook
      tag: latest
      pullPolicy: Always
    env:
      - name: LOG_LEVEL
        value: debug
      - name: LOG_FORMAT
        value: txt
#      - name: DRY_RUN
#        value: "true"
#      - name: DOMAIN_FILTER
#        value: "alexkrieg.com,alexkrieg.de"
#      - name: EXCLUDE_DOMAIN_FILTER
#        value: "test.com,test.de"
#      - name: REGEXP_DOMAIN_FILTER
#        value: ""
#      - name: REGEXP_DOMAIN_FILTER_EXCLUSION
#        value: ""
      - name: IONOS_API_KEY
        value: "test-api-key"
      - name: IONOS_API_URL
        value: "http://mockserver.mockserver.svc.cluster.local:1080"
      - name: IONOS_DEBUG
        value: "true"
