image:
  tag: v0.15.0

# -- ExternalDNS Log level.
logLevel: debug

# -- Interval for DNS updates.
interval: 1m

namespaced: false

rbac:
  # -- If `true`, create a `ClusterRole` & `ClusterRoleBinding` with access to the Kubernetes API.
  create: true

# -- _Kubernetes_ resources to monitor for DNS entries.
sources:
  - ingress
  - service

# -- How DNS records are synchronized between sources and providers; available values are sync & upsert-only.
policy: upsert-only

## - Limit possible target zones by domain suffixes.
domainFilters:
  - test.com

## -- Intentionally exclude domains from being managed.
excludeDomains: []

extraArgs:
  ## must override the default value 8888 as port 8080 is hard-coded in the helm chart
  - --webhook-provider-url=http://localhost:8080

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/ionos-cloud/external-dns-ionos-webhook
      tag: v0.6.1
    env:
      - name: LOG_LEVEL
        value: debug
      - name: IONOS_API_KEY
        valueFrom:
          secretKeyRef:
            name: ionos-credentials
            key: api-key
      - name: SERVER_HOST
        value: "0.0.0.0"
      - name: SERVER_PORT
        value: "8080"
      - name: IONOS_DEBUG
        value: "false"
      - name: DOMAIN_FILTER
        value: alexkrieg.com
      - name: DRY_RUN
        value: "true"
    livenessProbe:
      httpGet:
        path: /health
    readinessProbe:
      httpGet:
        path: /health

