app:
  logLevel: "DEBUG"

service:
  type: "ClusterIP"
  port: 1080

ingress:
  enabled: true
  className: "nginx"
  hosts:
  - host: mockserver.local
    paths:
    - path: "/"
      pathType: ImplementationSpecific